

spring.application.name=telegram-bot
spring.datasource.url=jdbc:postgresql://localhost:5433/telegram
spring.datasource.username=telegram_boy
spring.datasource.password=tegeshka
spring.jpa.hibernate.ddl-auto=update
telegram.bot.token=7912688672:AAF2VnUll4mfvd1GMGiZwKtHkk-xDLL2RCM